"""Create initial tables

Revision ID: 590f779eebc8
Revises: 
Create Date: 2025-02-21 17:04:39.419553

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '590f779eebc8'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ### 