"""add destination field to trip model

Revision ID: 93f73f15bcc1
Revises: e3cadbde6cff
Create Date: 2025-02-21 21:58:05.437649

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '93f73f15bcc1'
down_revision = 'e3cadbde6cff'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # Add the column as nullable first
    op.add_column('trips', sa.Column('destination', sa.String(length=255), nullable=True))
    
    # Update existing records with a default value
    op.execute("UPDATE trips SET destination = 'Unknown' WHERE destination IS NULL")
    
    # Make the column non-nullable
    op.alter_column('trips', 'destination',
                    existing_type=sa.String(length=255),
                    nullable=False)


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('trips', 'destination')
    # ### end Alembic commands ###